#!/usr/bin/env python3
"""
Пакетный парсер регистров AM335x для координатного PDF (spruh73q.pdf)
Установка: pip install PyMuPDF

Использование:
  # По диапазону страниц
  python parse_registers_batch.py spruh73q.pdf --pages 1465-1476 --output control_module.h

  # По списку регистров из файла
  python parse_registers_batch.py spruh73q.pdf --list registers.txt --output all_regs.h
"""

import sys
import re
import argparse
from parse_register import CoordinatedPDFParser


class BatchRegisterParser(CoordinatedPDFParser):
    """Расширенный парсер с возможностью поиска всех регистров на страницах"""

    def find_all_registers_on_pages(self, start_page: int, end_page: int) -> list:
        """
        Находит все регистры в заданном диапазоне страниц
        Возвращает список словарей с информацией о регистрах
        """
        registers = []
        seen_registers = set()

        print(f"[INFO] Поиск регистров на страницах {start_page}-{end_page}")

        for page_num in range(start_page - 1, min(end_page, len(self.doc))):
            page = self.doc[page_num]
            text = page.get_text()

            # Ищем все упоминания регистров на странице
            pattern = r'([a-z0-9_]+)\s+Register\s*\(offset\s*=\s*([0-9a-fA-F]+h)\)\s*\[reset\s*=\s*([0-9a-fA-F]+h)\]'
            matches = re.finditer(pattern, text, re.IGNORECASE)

            for match in matches:
                reg_name = match.group(1)

                # Пропускаем уже найденные регистры
                if reg_name in seen_registers:
                    continue

                print(f"[INFO] Найден регистр '{reg_name}' на странице {page_num + 1}")

                # Используем существующий метод для полного парсинга
                reg_info = self.find_register(reg_name)
                if reg_info:
                    registers.append(reg_info)
                    seen_registers.add(reg_name)

        return registers

    def find_registers_from_list(self, reg_list: list) -> list:
        """Парсит список регистров и возвращает их информацию"""
        registers = []

        for reg_name in reg_list:
            reg_name = reg_name.strip()
            if not reg_name or reg_name.startswith('#'):
                continue

            print(f"\n[INFO] Обработка регистра '{reg_name}'")
            reg_info = self.find_register(reg_name)
            if reg_info:
                registers.append(reg_info)
            else:
                print(f"[WARN] Регистр '{reg_name}' не найден")

        return registers


def generate_combined_header(registers: list, module_name: str = "registers", base_address: str = "0x0") -> str:
    """Генерирует объединённый заголовочный файл в стиле структуры с reserved полями"""
    lines = []

    # Заголовок файла
    lines.append("/**")
    lines.append(f" * @file {module_name}.h")
    lines.append(" * @brief Register definitions for AM335x")
    lines.append(" * @note Auto-generated by parse_registers_batch.py")
    lines.append(" * @note Source: spruh73q.pdf (AM335x TRM)")
    lines.append(" */")
    lines.append("")
    lines.append(f"#ifndef _{module_name.upper()}_H_")
    lines.append(f"#define _{module_name.upper()}_H_")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")

    # Макросы для доступа
    lines.append("#define __R     volatile const")
    lines.append("#define __W     volatile")
    lines.append("#define __RW    volatile")
    lines.append("")

    lines.append("#ifdef __cplusplus")
    lines.append("extern \"C\" {")
    lines.append("#endif")
    lines.append("")

    # Генерируем typedef union для каждого регистра с комментарием о смещении и сбросе
    for reg_info in registers:
        reg_name = reg_info['name']
        offset_hex = reg_info['offset'].rstrip('h').rstrip('H')
        if not offset_hex.startswith('0x'):
            offset_hex = f"0x{offset_hex}"
        reset_hex = reg_info['reset'].rstrip('h').rstrip('H')
        if not reset_hex.startswith('0x'):
            reset_hex = f"0x{reset_hex}"

        # Добавляем комментарий с информацией о регистре
        lines.append(f"/* (offset = {offset_hex}) [reset state = {reset_hex}] */")

        # Генерируем union для регистра
        temp_parser = CoordinatedPDFParser("")
        reg_code = temp_parser.generate_c_code(reg_info)

        # Извлекаем только union часть (пропускаем первую строку с комментарием)
        reg_lines = reg_code.split('\n')
        union_start = 0
        for i, line in enumerate(reg_lines):
            if 'typedef union' in line:
                union_start = i
                break

        # Добавляем union
        for line in reg_lines[union_start:]:
            lines.append(line)

        lines.append("")
        lines.append("")

    # Генерируем общую структуру модуля с reserved полями и комментариями смещений
    if registers:
        # Определяем максимальную длину имени типа для выравнивания
        max_type_len = max(len(f"{reg['name']}_reg_t") for reg in registers)
        max_type_len = max(max_type_len, 10)  # минимум для "uint32_t"

        lines.append(f"typedef struct")
        lines.append("{")

        current_offset = 0
        # Сортируем регистры по смещению
        sorted_regs = sorted(registers, key=lambda r: int(r['offset'].rstrip('h').rstrip('H'), 16))

        reserved_counter = 0

        for reg_info in sorted_regs:
            reg_name = reg_info['name']
            offset = int(reg_info['offset'].rstrip('h').rstrip('H'), 16)

            # Добавляем reserved если есть пропуск
            if offset > current_offset:
                reserved_size = (offset - current_offset) // 4
                reserved_counter += 1
                suffix = f"_{reserved_counter}" if reserved_counter > 1 else ""

                if reserved_size == 1:
                    lines.append(
                        f"    __R  uint32_t{' ' * (max_type_len - 8)}RESERVED{suffix};{' ' * (30 - len(f'RESERVED{suffix}'))}// ({current_offset:04X})")
                else:
                    lines.append(
                        f"    __R  uint32_t{' ' * (max_type_len - 8)}RESERVED{suffix}[{reserved_size}];{' ' * (30 - len(f'RESERVED{suffix}[{reserved_size}]'))}// ({current_offset:04X}..{offset - 4:04X})")
                current_offset = offset

            # Добавляем регистр с комментарием смещения
            reg_type = f"{reg_name}_reg_t"
            padding = max_type_len - len(reg_type)
            lines.append(
                f"    __RW {reg_type}{' ' * padding} {reg_name};{' ' * (30 - len(reg_name))}// ({current_offset:04X})")
            current_offset += 4

        # Добавляем reserved в конце если нужно (до ближайшей границы или просто оставляем как есть)
        # Обычно модуль может иметь фиксированный размер, но здесь просто завершаем структуру

        lines.append(f"}} AM335x_{module_name.upper()}_Type;")
        lines.append("")

        # Добавляем проверку размера структуры (опционально)
        lines.append(f"#define {module_name.upper()}_SIZE 0x{current_offset:04X}")
        lines.append("")

        # Добавляем базовые адреса
        lines.append(f"constexpr uint32_t {module_name.upper()}_BASE = {base_address};")
        lines.append(
            f"constexpr AM335x_{module_name.upper()}_Type * {module_name.upper()} = ((AM335x_{module_name.upper()}_Type *) {module_name.upper()}_BASE);")
        lines.append("")

    lines.append("#ifdef __cplusplus")
    lines.append("}")
    lines.append("#endif")
    lines.append("")
    lines.append(f"#endif /* _{module_name.upper()}_H_ */")

    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Пакетный парсер регистров AM335x",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Примеры:
  # Парсинг диапазона страниц
  python parse_registers_batch.py spruh73q.pdf --pages 1465-1476 --output control_module.h --module-name CONTROL --base-address 0x44E10000

  # Парсинг из файла со списком регистров
  python parse_registers_batch.py spruh73q.pdf --list regs.txt --output all_regs.h --module-name I2C --base-address 0x44E0B000

Формат файла со списком регистров (regs.txt):
  # Это комментарий
  control_status
  control_sysconfig
  mosc_ctrl
  control_emif_sdram_config
        """
    )

    parser.add_argument("pdf_file", help="Путь к PDF файлу (spruh73q.pdf)")
    parser.add_argument("--pages", help="Диапазон страниц (например: 1465-1476)")
    parser.add_argument("--list", dest="list_file", help="Файл со списком регистров (по одному на строку)")
    parser.add_argument("--output", "-o", default="registers.h", help="Выходной файл (по умолчанию: registers.h)")
    parser.add_argument("--module-name", default="registers", help="Имя модуля для заголовка")
    parser.add_argument("--base-address", default="0x0", help="Базовый адрес модуля (например: 0x44E10000)")

    args = parser.parse_args()

    # Проверяем аргументы
    if not args.pages and not args.list_file:
        print("[ERROR] Необходимо указать --pages или --list")
        sys.exit(1)

    print(f"[INFO] Загрузка PDF: {args.pdf_file}")
    batch_parser = BatchRegisterParser(args.pdf_file)

    registers = []

    if args.pages:
        # Парсим диапазон страниц
        match = re.match(r'(\d+)-(\d+)', args.pages)
        if not match:
            print("[ERROR] Неверный формат диапазона страниц. Используйте: 1465-1476")
            sys.exit(1)

        start_page = int(match.group(1))
        end_page = int(match.group(2))

        if start_page > end_page:
            print("[ERROR] Начальная страница должна быть меньше конечной")
            sys.exit(1)

        registers = batch_parser.find_all_registers_on_pages(start_page, end_page)

    elif args.list_file:
        # Читаем список регистров из файла
        try:
            with open(args.list_file, 'r') as f:
                reg_list = f.readlines()
            registers = batch_parser.find_registers_from_list(reg_list)
        except FileNotFoundError:
            print(f"[ERROR] Файл '{args.list_file}' не найден")
            sys.exit(1)

    if not registers:
        print("[ERROR] Не найдено ни одного регистра")
        sys.exit(1)

    print(f"\n[INFO] Всего обработано регистров: {len(registers)}")

    # Генерируем объединённый заголовочный файл
    print(f"[INFO] Генерация {args.output}")
    header_content = generate_combined_header(registers, args.module_name, args.base_address)

    with open(args.output, 'w') as f:
        f.write(header_content)

    print(f"[OK] Сохранено в: {args.output}")

    # Выводим статистику
    total_fields = sum(len(r['fields']) for r in registers)
    print(f"\n[STAT] Всего регистров: {len(registers)}")
    print(f"[STAT] Всего полей: {total_fields}")


if __name__ == "__main__":
    main()